config/routes.rb
Ancestry::Application.routes.draw do
  
  root 'main#page'
  
  resources :texts

  

end

app/models/text.rb
class Text < ActiveRecord::Base
  has_ancestry

  extend FriendlyId
  friendly_id :title, use: :finders

  def self.root
    Text.where(title: ROOT).first_or_create
  end
  ROOT = 'root'

  after_create do
    unless parent
      self.parent = Text.root
      save
    end
  end

  # ancestry stuff:
  #
  ARRANGE = { order: 'title' }

  def self.arrange_as_array(hash)
    arr = []
    hash.each do |node, children|
      arr << [node.name_for_selects, node.id]
      arr += arrange_as_array(children) unless children.nil?
    end
    arr
  end

  NBSP = 0xC2.chr + 0xA0.chr
  INDENT = NBSP*3  #?∙ #'·' * 2 #—
  def name_for_selects
    "#{INDENT * depth} #{title}"
  end

  def possible_parents
    Text.arrange ARRANGE
    #parents = Text.arrange_as_array Text.arrange ARRANGE
    #return new_record? ? parents : parents - subtree
  end

  def arrange_as_array
    Text.arrange_as_array possible_parents
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def page
    @root = Text.root
    @texts = Text.where.not(id: @root.id).order('random()').take(5)

    @q = Text.search
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy]

  # GET /texts
  # GET /texts.json
  def index
    @q = Text.search params[:q]
    @texts = @q.result distinct: true
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
  end

  # GET /texts/new
  def new
    @text = params[:text] ? Text.new(text_params) : Text.new
    @texts = @text.arrange_as_array
  end

  # GET /texts/1/edit
  def edit
    @texts = @text.arrange_as_array
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)

    respond_to do |format|
      if @text.save
        format.html { redirect_to @text, notice: 'Text was successfully created.' }
        format.json { render action: 'show', status: :created, location: @text }
      else
        format.html { render action: 'new' }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: 'Text was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    redirect_to @text, notice: 'nope...'
    #parent = @text.parent
    #@text.destroy
    #respond_to do |format|
    #  format.html { redirect_to parent || texts_url }
    #  format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.require(:text).permit(:title, :body, :parent_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def crumbs *a
    a.map { |x|
      case x
      when :home then
        ['home', ?/]
      when :texts then
        ['texts', texts_path]
      when :new then
        ['new child', nil]
      when Text then
        [x.title, x]
      else throw end
    }
  end

  def breadcrumbs *given
    content_for :breadcrumbs do
      render partial: 'breadcrumbs', locals: {
        given: crumbs(*given)
      }
    end
  end

  def the_title
    if content_for?(:title)
      content_for :title
    else
      if content_for?(:header)
        content_for :header
      else
        '...'
      end
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/texts_helper.rb
module TextsHelper
  def header_link_to title, object, options = {}
    options = { class: 'tiny secondary round button' }
              .merge options
    link_to title, object, options
  end
end

app/views/application/_breadcrumbs.html.slim
- is_last = given[0...-1].map { false } + [ true ]

- given.zip(is_last).each do |data,last|
  - if last
    = link_to *data, class: 'current'
  - else
    = link_to *data

app/views/application/_explore_words.html.slim
h2 = link_to 'Explore words'

table.full
  tr 
    td random
  tr 
    td words
  tr 
    td here

form
  div.row.collapse
    div.small-9.columns
      input type='text'
    div.small-3.columns
      span.postfix.radius.button
        'find

app/views/application/_main.html.slim
section role='main'
  header
    .row
      h1 style='display: inline-block'
        = content_for :header
        = content_for :header_links

  - if content_for? :breadcrumbs
    nav.breadcrumbs
      = content_for :breadcrumbs

  .row
    p
    /hr

  == yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= the_title %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render partial: 'main' %>
    <%#= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/main/_contribute.html.slim
= image_tag 'box.png', alt: 'not ready yet'

/h2 
  a href='/how-to-contribute' Contribute

/table.full
  tr
    td 
      a how to add texts
  tr
    td 
      a how to link them
  tr
    td 
      a how to upload media

/form
  .row.collapse
    .small-5.columns
      input type='text' placeholder='login'
    .small-5.columns
      input type='text' placeholder='pass'
    .small-2.columns
      span.postfix.radius.button.arrow.secondary
        '❯

app/views/main/_explore_texts.html.slim
h2 = link_to 'Explore texts', text_path(@root)

table.full
  - @texts.each do |text|
    tr
      td = link_to text.title, text


= render partial: '/texts/search_form'

app/views/main/_explore_words.html.slim
= image_tag 'box.png', alt: 'not ready yet'

/h2 = link_to 'Explore words'

/table.full
  tr
    th pi(flag?)
    th ru
    th en
  tr 
    td 
      a random
    td 
      a random
    td 
      a random
  tr 
    td 
      a words
    td 
      a words
    td 
      a words
  tr 
    td 
      a here
    td 
      a here
    td 
      a here

/form
  div.row.collapse
    div.small-9.columns
      input type='text'
    div.small-3.columns
      span.postfix.radius.button.secondary
        'find

app/views/main/page.html.slim
- content_for :header do '...' end
- breadcrumbs :home

.row
  /.small-block-grid-2.large-block-grid-3
  .large-4.columns
    .panel
      = render partial: 'explore_words'
  .large-4.columns
    .panel
      = render partial: 'explore_texts'
  .large-4.columns
    .panel
      = render partial: 'contribute'

app/views/texts/_form.html.slim
= semantic_form_for @text do |f|
  - if @text.errors.any?
    #error_explanation
      h2 = "#{pluralize(@text.errors.count, "error")} prohibited this text from being saved:"
      ul
        - @text.errors.full_messages.each do |message|
          li = message

  /.actions = f.submit 'Save'
  /'Text' do
  = f.inputs do
    = f.input :title
    = f.input :body
    = f.input :parent_id, as: :select, collection: @texts, label: :parent, include_blank: false
    /= f.select :parent_id, @texts, label: 'parent', member_label: 'parent_id'

    /= f.select :parent_id, [['US', 2], ['Canada', 3]]
    /= f.input :parent, :as => :select, :collection => option_groups_from_collection_for_select(Text.all, :texts, :name, :id, :name)
  = f.actions

app/views/texts/_search_form.html.slim
- q = @q

= search_form_for q do |f|
  .row.collapse
    /= f.label :title_or_body_cont
    .small-9.columns
      = f.text_field :title_or_body_cont, placeholder: 'title or body contains'
    .small-3.columns  
      = f.submit class: 'postfix radius secondary button', value: 'find'

app/views/texts/edit.html.slim
- content_for :header do "editing #{@text.title}" end
- content_for :header_links do
  = header_link_to 'view', @text
  = header_link_to 'add child', new_text_path(text: {parent_id: @text.friendly_id})
  = header_link_to 'destroy', @text, method: :delete

.row
  == render 'form'

app/views/texts/index.html.slim
- content_for :header do 'listing texts, chapters, categories' end
- breadcrumbs :home, :texts


.row.large-4
  = render partial: 'search_form'


.row
  table.full
    /tr
      th
  
    - @texts.each do |text|
      tr
        td = link_to text.title, text

app/views/texts/new.html.slim
- content_for :header do 'New text' end
- path = @text.try(:path) || []
- path = path.empty?? [] : [:texts] + path
- breadcrumbs :home, *path, :new

.row
  == render 'form'

app/views/texts/show.html.slim
- content_for :header do @text.title end
- content_for :header_links do
  = header_link_to 'edit', edit_text_path(@text)
- breadcrumbs :home, :texts, *@text.path

- if notice
  .row
    p.success.round.label#notice = notice

.row    
  p = @text.body
  
  
.row  
  table.full
    - @text.children.each do |child|
      tr
        td
          = link_to child.title, child